### PR TITLE
Show transfer rate in downloads panel

### PR DESCRIPTION
**Pull request by wsdfhjxc**
This was requested by several users in the past. The downloads panel is now slightly wider but it's possible to take a quick look at downloaded entries to find out their transfer rates.

### CODE REVIEW

**Comment by wolfbeast** [comment]
Looks OK, a few things:
- Nit: please don't add statements like "because why not" That's not the kind of arbitrary reasoning I want in Pale Moon ;) Either don't add a because, or make it a solid reason.
- If we can avoid cutting off text, we should. The panel should be sized to the maximum width that could occur in the long string. If that's visually too wide for comfort, then this needs a different solution (e.g. make the string composition function different to take less space).

**Comment by Antonius32** [comment]
I don't think this is an improvement. If we're going to show all information in the Downloads panel (transfer rate, site indicator - both of which can currently be viewed by showing the download details' / download display name's tooltip), and change the size of the Downloads panel to make it all fit in, I think we might as well disable the Downloads section within the Library, which can be accessed by clicking "Show All Downloads", and which displays all available details in its downloads overview. Besides, if a user wants to have one-click access to all details about their (in-progress) downloads, they can simply switch to the classic Downloads window (once this functionality is restored in Tycho).

Just my opinion on this..

**Comment by wsdfhjxc** [comment]
You might be right. This was initially designed this way by Mozilla not without a proper reason, as this panel is just an addition to the toolbar, so it should be simple. I personally don't use regular downloads window anymore because of this panel, but I do realize that such a change may be reduntant and disliked by some users. So, yes, just reject this. I think I shouldn't even bother you with such PRs, especially at this stage of development :)

**Comment by wolfbeast** [comment]
I had a look at the final result and it really does clutter things and makes it too wide for comfort. I do appreciate greatly that you want to help and try to improve the browser -- this one unfortunately isn't particularly an improvement. So I guess we're all in agreement ;)

Closing.

**Comment by Antonius32** [comment]
If the classic Downloads window is going to be left out in Tycho, then I wouldn't be opposed to this change, but I think we should show the site indicator in the Downloads panel as well, then (not just in the download display name's tooltip).

**Comment by wolfbeast** [comment]
The reasoning behind this had nothing to do with the classic downloads window.

**Pull request closed without merging**
