### PR TITLE
Disallow Jetpack/SDK extensions to be installed and used

### PR DESCRIPTION
**Pull request by wsdfhjxc**
Assuming that extensions of this kind are no longer supported and they will not work at all anymore.

### CODE REVIEW

**Comment by wolfbeast** [comment]
Simple and efficient -- I approve :)
The only thing it still needs is having a proper message for the user in the notification doorhanger.

**Comment by mattatobin** [comment]
My only nit is the use of "jetsdk" instead of "jetpack" but I can live with it.. No need to go back and edit it.. Unless you really want to..

**Comment by wsdfhjxc** [comment]
Unfortunately this only prevents new Jetpack/SDK extensions from being installed.

I might be wrong but it seems that already installed extensions are validated against their stored JSON metadata -- eg. when they are being checked after the browser update the new _appVersion_ is compared with their previously cached _maxVersion_ properties inside extensions.json (when _strictCompatibility_ is active). In those extensions there is no Jetpack/SDK verification because _jetsdk_ property is missing and it is set only when an .xpi archive is being parsed (the aZipReader part) and this happens when an extension file is opened just before installing. So, if previously installed extensions had to be checked for Jetpack/SDK rubbish then their .xpi files have to be reopened and parsed once again, because there are no other JSON markers telling about Jetpack/SDK relations. Correct me if something's totally incorrect.

I guess this should be rejected and you'll eventually make a proper workaround, especially that it's a little bit more serious than it seemed and obviously you know better how to modify compatibility subsystem so it does mentioned above checkings efficiently, without breaking anything else :)

**Comment by mattatobin** [comment]
Fair enough.. Just was wondering. Good job in any case!

**Comment by wsdfhjxc** [comment]
Last thing I'd like to know - does compatibility checker which runs after the browser update do the same thing as compatibility check refresh after toggling _strictCompatibility_ preference? I remember it does some heavy job according to a progressbar in its window, but again I didn't really check it and I'm not sure if it's the same. Is there a way to force it to run before launching the browser, any command line parameter or something?

**Comment by mattatobin** [comment]
I do not believe there is a way to force it to run by command line.. The only way I know to potentially have it run is if the version and milestone preferences are cleared or are lower(also maybe higher) than current.

**Comment by wolfbeast** [comment]
Merged this in since it's a good safeguard for users who otherwise would not know that it isn't a compatible type when installing. We should probably do a similar thing for WebExtensions.

**Comment by mattatobin** [comment]
No need.. They simply aren't valid least by default.. Do we even have some of the start of that inferior extension framework in the codebase?

**Comment by wolfbeast** [comment]
No, we don't have anything for WEX in our code base, I don't think.

**Comment by wsdfhjxc** [comment]
I've figured out that compatibility check after the browser update behaves different than compatibility check after toggling _strictCompatibility_ preference. 

The one after a browser update causes `addMetadata` method to be called for each add-on. It's possible to force an update of metadata here by inserting `updateMetadata(installLocation, aOldAddon, xpiState);` before [XPIProvider.jsm#L3438](https://github.com/MoonchildProductions/Tycho/tree/master/toolkit/mozapps/extensions/internal/XPIProvider.jsm#L3438). It actually reloads the install manifest file which leads to _jetsdk_ property assignment on the occasion. After this there is a call to `updateVisibilityAndCompatibility` which makes an assignment `aOldAddon.appDisabled = !isUsableAddon(aOldAddon);` somewhere inside. This results in disabling previously installed Jetpack/SDK extensions at the browser startup preceded by compatibility checker run for example after an application update.

However, the compatibility check after toggling _strictCompatibility_ preference causes `updateAddonAppDisabledStates` method to be called which calls the proper one for each add-on which is [XPIProvider.jsm#L4502](https://github.com/MoonchildProductions/Tycho/tree/master/toolkit/mozapps/extensions/internal/XPIProvider.jsm#L4502). This method also contains the usability assignment mentioned above but it seems that _jetsdk_ property is not remembered at the moment of executing this method (maybe it isn't automatically rewritten from JS object to JSON cache in contrary to _blocklistState_ for example). This results in enabling these disabled Jetpack/SDK extensions whenever _strictCompatibility_ preference is being toggled.

**Comment by mattatobin** [comment]
Disregarding the strictCompatiblity pref for the moment.. It sounds like browser upgrade triggered add-on checking will serve to disable jetpack extensions as an added bonus to the patch you submitted.. I think this is sufficient assuming I am understanding you properly.

**Pull request merged**
