### PR TITLE
Backport some BSD fixes

### PR DESCRIPTION
**Pull request by jbeich**
Similar to MoonchildProductions/Pale-Moon#468. Here's how to test (with workarounds):

DragonFly 4.5
```sh
$ echo 'ac_add_options --with-system-nspr' >>.mozconfig
$ ln -sf FreeBSD.mk security/nss/coreconf/DragonFly$(uname -r).mk
$ pkg install nspr python27
$ ./mach bootstrap
$ nice ./mach build
$ ./mach run https://mozilla.github.io/webrtc-landing/data_test.html
```
FreeBSD 10.3 (clang)
```sh
$ pkg install python27
$ ./mach bootstrap
$ nice ./mach build
$ ./mach run https://mozilla.github.io/webrtc-landing/data_test.html
```
FreeBSD 10.3 (gcc)
```sh
$ echo 'export CC=gcc5 CXX=g++5 CPP=cpp5' >>.mozconfig
$ pkg install gcc5 python27
$ ./mach bootstrap
$ nice ./mach build
$ ./mach run https://mozilla.github.io/webrtc-landing/data_test.html
```

Note, FreeBSD 10+ uses clang/libc++ by default. Building with gcc/libstdc++ isn't recommended as one of dependencies may pull libc++ leading to crashes. libstdc++ has to be linked against libcxxrt but so far neither upstream GCC nor lang/gcc* port(s) have been fixed.

### CODE REVIEW

**Comment by wolfbeast** [comment]
Had to back this out because of build bustage on Windows.

**Comment by mattatobin** [comment]
Alright.. @jbeich..

You are seriously going to have to consider and respect the fact that the codebase is a cross platform codebase and that Windows, Linux, and Mac cannot be busted to get a working BSD build.

You have two choices in this regard. You can maintain your own branch and deal with merge conflicts from upstream (Us) or you must ensure that your modifications submitted to our codebase do not interfere, radically change behavior, or block our officially supported platforms.

Which means you are going to have reasonably prove to us before a Pull Request is made that you have gone the length and tested that nothing you have added or changed will throw us into a bugstage.

While we would love to boast that we are BSD compatible it cannot come at a cost of our primary platforms or headaches of constant reversion of commits.. We strive to keep our commit history straight forward and not fall into the trap of a million commit revert commit revert until "the tree is green".

**Comment by jbeich** [comment]
What's Try server equivalent for Tycho/Palemoon? For one, projects on GitHub often use Travis. Breakage is an ordinary occurence for complex changes or with too many commits in one PR where CI helps to know and block merge in advance.

#93 is likely due to 9ad73bb475f1 but I don't have Windows machine nearby to confirm.

**Comment by jbeich** [comment]
Testing after backing out 9ad73bb isn't conclusive even if Linux and OS X are green. Try appears to no longer support building mozilla-esr38 on Android and Windows:
https://treeherder.mozilla.org/#/jobs?repo=try&revision=ee10d65c8e5c

**Pull request merged**
