### PR TITLE
Remove Mozilla crashreporter & SPS Profiler

### PR DESCRIPTION
**Pull request by trav90**
I've been working on ripping out the Mozilla crashreporter. This PR removes it, with the exception of in tests/mochitests (which I will followup on once this is complete). I've hit some build bustage that I haven't been able to solve after working on it over the past few days, so I've decided to go ahead and submit this PR as a "WIP", hoping that someone would be able to point me in the right direction to get this fixed. Build error is:

```
In file included from /home/trava90/src/Tycho/pmbuild/dom/ipc/Unified_cpp_dom_ipc0.cpp:119:0:
 7:27.38 /home/trava90/src/Tycho/Tycho-kill-crashreporter/dom/ipc/TabChild.cpp: In member function ‘virtual nsresult mozilla::dom::ContentListener::HandleEvent(nsIDOMEvent*)’:
 7:27.38 /home/trava90/src/Tycho/Tycho-kill-crashreporter/dom/ipc/TabChild.cpp:565:18: error: aggregate ‘mozilla::dom::RemoteDOMEvent remoteEvent’ has incomplete type and cannot be defined
 7:27.38    RemoteDOMEvent remoteEvent;
 7:27.38                   ^
 7:30.71 In the directory  /home/trava90/src/Tycho/pmbuild/dom/ipc
 7:30.71 The following command failed to execute properly:
 7:30.71 /usr/bin/g++-4.9 -o Unified_cpp_dom_ipc0.o -c -I../../dist/stl_wrappers -I../../dist/system_wrappers -include /home/trava90/src/Tycho/Tycho-kill-crashreporter/config/gcc_hidden.h -DOS_POSIX=1 -DOS_LINUX=1 -DBIN_SUFFIX="" -DMOZ_ENABLE_FREETYPE -DMOZ_TOOLKIT_SEARCH -DMOZ_PERMISSIONS -DSTATIC_EXPORTABLE_JS_API -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL -DMOZ_GLUE_IN_PROGRAM -DAB_CD=en-US -DNO_NSPR_10_SUPPORT -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/dom/ipc -I. -I/home/trava90/src/Tycho/pmbuild/ipc/ipdl/_ipdlheaders -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/ipc/chromium/src -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/ipc/glue -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/caps -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/chrome -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/docshell/base -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/dom/base -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/dom/bluetooth -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/dom/bluetooth/ipc -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/dom/devicestorage -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/dom/filesystem -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/dom/fmradio/ipc -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/dom/geolocation -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/dom/media/webspeech/synth/ipc -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/dom/mobilemessage/ipc -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/dom/storage -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/dom/workers -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/editor/libeditor -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/embedding/components/printingui/ipc -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/extensions/cookie -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/extensions/spellcheck/src -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/hal/sandbox -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/layout/base -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/netwerk/base -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/toolkit/xre -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/uriloader/exthandler -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/widget -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/xpcom/base -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/xpcom/threads -I../../dist/include -I/home/trava90/src/Tycho/pmbuild/dist/include/nspr -I/home/trava90/src/Tycho/pmbuild/dist/include/nss -fPIC -DMOZILLA_CLIENT -include ../../mozilla-config.h -MD -MP -MF .deps/Unified_cpp_dom_ipc0.o.pp -Wall -Wempty-body -Woverloaded-virtual -Wsign-compare -Wwrite-strings -Wno-invalid-offsetof -Wcast-align -O2 -msse2 -mfpmath=both -march=x86-64 -floop-parallelize-all -fpredictive-commoning -ftree-loop-distribution -ftree-vectorize -fno-exceptions -fno-strict-aliasing -fno-rtti -ffunction-sections -fdata-sections -fno-exceptions -fno-math-errno -std=gnu++0x -pthread -pipe -DNDEBUG -DTRIMMED -g -freorder-blocks -Os -fomit-frame-pointer -I/home/trava90/src/Tycho/Tycho-kill-crashreporter/widget/gtk/compat -pthread -I/usr/include/gtk-2.0 -I/usr/include/gtk-unix-print-2.0 -I/usr/include/gtk-2.0 -I/usr/include/atk-1.0 -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include /home/trava90/src/Tycho/pmbuild/dom/ipc/Unified_cpp_dom_ipc0.cpp
 7:30.71 /home/trava90/src/Tycho/Tycho-kill-crashreporter/config/rules.mk:936: recipe for target 'Unified_cpp_dom_ipc0.o' failed
 7:30.71 make[5]: *** [Unified_cpp_dom_ipc0.o] Error 1
 7:30.72 /home/trava90/src/Tycho/Tycho-kill-crashreporter/config/recurse.mk:74: recipe for target 'dom/ipc/target' failed
 7:30.72 make[4]: *** [dom/ipc/target] Error 2
 7:30.72 make[4]: *** Waiting for unfinished jobs....
```

### CODE REVIEW

**Comment by Axiomatic-** [comment]
@trav90 try this for the build error:
```patch
diff --git a/dom/ipc/TabParent.h b/dom/ipc/TabParent.h
index 10d4237..a4695dd 100644
--- a/dom/ipc/TabParent.h
+++ b/dom/ipc/TabParent.h
@@ -23,6 +23,8 @@
 #include "WritingModes.h"
 #include "js/TypeDecls.h"

+#include "TabMessageUtils.h"
+
 class nsFrameLoader;
 class nsIFrameLoader;
 class nsIContent;
```

**Comment by Axiomatic-** [comment]
@trav90 try this for the build error:
```patch
diff --git a/dom/ipc/TabParent.h b/dom/ipc/TabParent.h
index 10d4237..a4695dd 100644
--- a/dom/ipc/TabParent.h
+++ b/dom/ipc/TabParent.h
@@ -23,6 +23,8 @@
 #include "WritingModes.h"
 #include "js/TypeDecls.h"

+#include "TabMessageUtils.h"
+
 class nsFrameLoader;
 class nsIFrameLoader;
 class nsIContent;
```

**Comment by trav90** [comment]
Thanks Axiomatic, that solves it. I knew it was something simple I was missing, just needed a fresh pair of eyes. The build still fails while looking for some Breakpad code that has been removed, so this is still a WIP and I'll update once I get it working.

**Comment by trav90** [comment]
An update: I've made some more progress on this and gotten past several build errors, but now I'm hitting a linker error. I've posted it below for reference.

```
31:55.60 ../../xpcom/threads/Unified_cpp_xpcom_threads0.o: In function `mozilla::ThreadStackHelper::Startup()':
31:55.60 /home/trava90/PaleMoon/Tycho/Tycho/xpcom/threads/ThreadStackHelper.cpp:50: undefined reference to `mozilla::ThreadStackHelper::sInitialized'
31:55.60 /opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.1/ld: ../../xpcom/threads/Unified_cpp_xpcom_threads0.o: relocation R_X86_64_PC32 against undefined hidden symbol `_ZN7mozilla17ThreadStackHelper12sInitializedE' can not be used when making a shared object
31:55.60 /opt/rh/devtoolset-3/root/usr/libexec/gcc/x86_64-redhat-linux/4.9.1/ld: final link failed: Bad value
31:55.60 collect2: error: ld returned 1 exit status
```

**Comment by wolfbeast** [comment]
Probably an issue because Mozilla never tests configurations with `#ifdef` settings other than what they release. Looks like part of the changes you made removed a default visibility -> hidden somewhere. Since the ::startup and ::shutdown functions are public, but the variables used in them are private (see threadstackhelper.h) you'll get this error.

I'm wondering though if we actually need the threadstackhelper to begin with?

In any case you should be able to work around this by making the dependent variables public in the stackthreadhelper header. I don't think there's any particular danger in doing that.

**Comment by trav90** [comment]
I changed the variables in ThreadStackHelper.h to public but it continues to fail with the same linker error.

> I'm wondering though if we actually need the threadstackhelper to begin with?

Short answer: I do not believe we do.

Long answer: the ThreadStackHelper was added in bug 935092 as a way for Mozilla to preserve the psuedo stack after a hang. It is tied into the background hang detector (bug 909974), which is tied into Moz telemetry (bug 932865).

**Comment by trav90** [comment]
Success! I've finally gotten this branch to build successfully with GCC 4.9 on my CentOS 6 box. With a quick test the build appears to be stable.

In addition to removing Mozilla's crash reporter, this PR also removes SPS Pofiler code, LSP Information gathering code, Google Breakpad, ThreadStackHelper & ThreadHangStats (used for telemetry), and reverts a few Mozilla bugs that tied the crash reporter/breakpad etc. into various areas of telemetry (I never realized how invasive the crashreporter/telemtry is!).

I am creating an issue in order to track the few remaining cleanups that need done.

**Comment by wolfbeast** [comment]
> I never realized before how invasive the crashreporter/telemtry actually is!

Yeah it's absolutely ridiculous, which is why I made a point before to try and rip most of that out. So much extra code for obsessive data gathering that shouldn't be in release versions of software...

**Comment by wolfbeast** [comment]
Before I merge this in, I'd like to check for issues building on Windows. Do you have a code point I can use to make a try build?

**Comment by trav90** [comment]
Yup, you can use the tip of my [kill-crashreporter](https://github.com/trav90/Tycho/tree/kill-crashreporter) branch; latest commit  b0bf165

**Comment by wolfbeast** [comment]
Okay, will do!

**Comment by wolfbeast** [comment]
Win build looks good. Great work, Travis!

**Comment by trav90** [comment]
Awesome!

**Pull request merged**
