### PR TITLE
Win10 Toolkit Theme Changes

### PR DESCRIPTION
**Pull request by Lootyhoof**
This updates the `listbox` and `tree` stylings for Windows 10. In doing so, it also replaces the PNGs used for `twisty` on Windows with SVGs instead, with a separate SVG for Windows 10 due to its different style. This also replaces defines within `listbox.css` and `tree.css` with CSS variables, in order to help reduce the amount of redundancy. The old `twisty` PNGs have been left for backwards-compatibility purposes (who knows if an addon uses these perhaps), plus they exist as fallback on the Linux theme (currently they are `-moz-appearance`'d there anyway). If you didn't want them to exist at all in the Windows theme though they could be easily moved to the Linux theme.

I also did some purging of `windows-xp` media queries which inadvertently slipped in when I was working on #107, as these came from upstream. These are probably fine to leave in, but redundant since we won't be supporting XP anyway.

### CODE REVIEW

**Comment by wolfbeast** [comment]
I don't have a quick way to verify this - can you show some "before" and "after" screenshots for these style changes?

**Comment by Lootyhoof** [comment]
I don't have a build with these baked in, but I did implement these (with variables expanded) into Australium. Before (in Tycho, sans this PR), on Windows 10:

PM27 default

After:

After

**Comment by wolfbeast** [comment]
Right - seeing the difference in color, is that drawn from the system theme then? I'm not entirely familiar with where these var()s are defined in the code.

**Comment by Lootyhoof** [comment]
These vars define the colour:

```
--treechildren-selectedColor: rgb(217,217,217);
--treechildren-focusColor: rgb(123,195,255);
--treechildren-selectedFocusColor: rgb(205,232,255);
--treechildren-currentColor: rgb(125,162,206);
--treechildren-hoverColor: rgb(229,243,255);
```
These are then overridden within the relevant `-moz-os-version` sections.

**Comment by wolfbeast** [comment]
Right, I get it.. And this is desirable over the previous setup because... no preprocessor?

**Comment by Lootyhoof** [comment]
This is partially true (developers can know exactly how the browser will see the styling, instead of figuring out how the defines work), but also to reduce the amount of redundancy present.

Consider the fact that there is no way within a define to check the OS version (since it's being preprocessed and therefore can't, by its nature, know where it'll be used). This then requires a define present for each style for each OS, with each of these styles defined multiple times for each OS. With CSS variables, these behave exactly as you would expect vars to work: they are defined and used within a generic context, then changed as required (in our case, within each `-moz-os-version` section accordingly). The styles themselves do not need to be redefined in each `-moz-os-version` section, as the properties are styled using the vars (so you only need to edit whichever vars need to change).

**Comment by wolfbeast** [comment]
You're absolutely correct. It does the same thing but then allowing conditional defines in the CSS itself (at runtime, not design time) to use different values. Thanks for the clarification!

**Pull request merged**
