### PR TITLE
The gcli cookie command - some fixes

### PR DESCRIPTION
**Pull request by janekptacijarabaci**
__The suggestion__

See bugs: [1042859](https://bugzilla.mozilla.org/show_bug.cgi?id=1042859), [1264993](https://bugzilla.mozilla.org/show_bug.cgi?id=1264993) and [1273835](https://bugzilla.mozilla.org/show_bug.cgi?id=1273835).

Btw, the same problem is also in Pale Moon (including the latest version 26).

Thank you in advance (if my suggestion is acceptable - before adding and testing).

If you want to add some tests... (if there are some important)

### CODE REVIEW

**Comment by wolfbeast** [comment]
Thank you!

**Comment by wolfbeast** [comment]
This is probably something we'd want uplifted to Pale Moon -release (since we'll likely have another minor release or two before Tycho is ready). Would you be willing to port this or should I?

**Comment by janekptacijarabaci** [comment]
> Would you be willing to port this or should I?

Please you do it yourself (I don't have this repository - now).
(https://github.com/MoonchildProductions/Pale-Moon/blob/master/browser/devtools/commandline/BuiltinCommands.jsm)

**Comment by wolfbeast** [comment]
Actually, directly porting this isn't possible, the code changes are N/A for our gcli implementation (we don't seem to have cookie handling in gcli).

**Comment by janekptacijarabaci** [comment]
So maybe I missed something but (here it begins):
https://github.com/MoonchildProductions/Pale-Moon/blob/26.4.0_Release/browser/devtools/commandline/BuiltinCommands.jsm#L809

The url: `https://www.github.com/`

__The command: `cookie list`__
(there is the invalid date)

palemoon_26 4 0_gcli-commands_cookie list

__After commands: `cookie remove logged_in` and `cookie set logged_in "a new value"`__

palemoon_26 4 0_gcli-commands_cookie list_after_cookie remove logged-in_and_cookie set logged-in a new value_1

__The menu: "Tools - Options - Privacy - History - Show cookies"__
(here is the correct date)

palemoon_26 4 0_gcli-commands_cookie list_after_cookie remove logged-in_and_cookie set logged-in a new value_2

**Comment by wolfbeast** [comment]
Ah. My bad, I was looking at the wrong xref (no devtools).

**Pull request merged**
