### PR TITLE
replace calls to String.prototype.contains with String.prototype.incl…

### PR DESCRIPTION
**Pull request by adisib**
This is a follow-up to commit 82c7acb762d3576a1bff00e017471d562527cb16 "Change String.prototype.contains to String.prototype.includes"

### CODE REVIEW

**Comment by wolfbeast** [comment]
Looks good! I assume you've done a build and functional testing with these changes?

**Comment by adisib** [comment]
Oh! I forgot to mention, sorry. I'm afraid my computer doesn't have enough memory to compile Pale Moon. This is untested. You will have to create a test build.

**Comment by wolfbeast** [comment]
Ah. Okay. Will have to keep this PR open and unmerged until it's been run through a try build (don't have time for that myself right now).

**Comment by wolfbeast** [comment]
Just made a try build and it all looks OK, so merging this in. Thanks!

**Comment by adisib** [comment]
Thanks for taking the time to test this for me.

**Pull request merged**
